name: Claude Code PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-claude-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Claude Code Action
        uses: ./.github/actions/claude-code-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Review the code changes in this PR and provide a comprehensive analysis. Format your response using the following structure with clear markdown section headers and bulleted lists within each section:

            ## 1. Description of Changes
            Provide a high-level summary of the PR changes. Include:
            * Main features or fixes being implemented
            * Technical approach used
            * Overall impact on the codebase

            ## 2. Potential Risks
            Identify any potential risks in these changes:
            * Possible edge cases that might not be handled
            * Performance concerns
            * Compatibility issues
            * Regression risks

            ## 3. Issues and Bugs
            Highlight any problems found in the code:
            * Potential bugs or logical errors
            * Missing validations or error handling
            * Edge cases not accounted for

            ## 4. Best Practices Suggestions
            Provide recommendations for improvement:
            * Code organization and structure improvements
            * Consistency with existing patterns in the codebase
            * Opportunities to improve readability and maintainability
            * Performance optimizations

            ## 5. Security Considerations
            Identify any security concerns:
            * Input validation issues
            * Potential injection vulnerabilities
            * Authentication/authorization controls
            * Data protection concerns

            IMPORTANT: Your response MUST strictly follow this format with numbered section headers and bulleted lists. Do not include any content outside these sections. Do not add additional sections or prefaces. Start directly with "## 1. Description of Changes" and end with the last item in the security section.
          allowed_tools: "Bash,GlobTool,GrepTool,LS,View,Edit,Replace,ReadNotebook,WebFetchTool"
          timeout_minutes: "15"