name: Claude Code PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      prompt_option:
        description: 'Select the prompt to use'
        required: true
        default: 'PR Summary'
        type: choice
        options:
          - 'PR Summary'
          - 'Code Review'
          - 'Security Audit'

permissions:
  contents: read
  pull-requests: write

jobs:
  run-claude-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Prompt
        id: set-prompt
        shell: bash
        run: |
          PROMPT_OPTION="${{ github.event.inputs.prompt_option || 'PR Summary' }}"
          
          if [[ "$PROMPT_OPTION" == "PR Summary" ]]; then
            PROMPT_PATH=".github/prompts/pr-summary.txt"
          elif [[ "$PROMPT_OPTION" == "Code Review" ]]; then
            PROMPT_PATH=".github/prompts/code-review.txt"
          elif [[ "$PROMPT_OPTION" == "Security Audit" ]]; then
            PROMPT_PATH=".github/prompts/security-audit.txt"
          fi
          
          echo "prompt=Please read and follow the instructions in $PROMPT_PATH to review this PR." >> $GITHUB_OUTPUT

      - name: Run Claude Code Action
        uses: ./.github/actions/claude-code-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: ${{ steps.set-prompt.outputs.prompt }}
          allowed_tools: "Bash,GlobTool,GrepTool,LS,View,Edit,Replace,ReadNotebook,WebFetchTool"
          timeout_minutes: "15"